// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/internal.proto

package ddb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Mutation_Type int32

const (
	Mutation_UNSPECIFIED Mutation_Type = 0
	Mutation_PUT         Mutation_Type = 1
	Mutation_DELETE      Mutation_Type = 2
)

var Mutation_Type_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "PUT",
	2: "DELETE",
}
var Mutation_Type_value = map[string]int32{
	"UNSPECIFIED": 0,
	"PUT":         1,
	"DELETE":      2,
}

func (x Mutation_Type) String() string {
	return proto.EnumName(Mutation_Type_name, int32(x))
}
func (Mutation_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

type LogRecord struct {
	Sequence int64     `protobuf:"varint,1,opt,name=sequence" json:"sequence,omitempty"`
	Mutation *Mutation `protobuf:"bytes,2,opt,name=mutation" json:"mutation,omitempty"`
}

func (m *LogRecord) Reset()                    { *m = LogRecord{} }
func (m *LogRecord) String() string            { return proto.CompactTextString(m) }
func (*LogRecord) ProtoMessage()               {}
func (*LogRecord) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *LogRecord) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *LogRecord) GetMutation() *Mutation {
	if m != nil {
		return m.Mutation
	}
	return nil
}

type Mutation struct {
	// The key associated with this mutation.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// The type of this mutation.
	Type Mutation_Type `protobuf:"varint,2,opt,name=type,enum=ddb.internal.Mutation_Type" json:"type,omitempty"`
	// Timestamp of this mutation.
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// For mutations that update, this is the value.
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Mutation) Reset()                    { *m = Mutation{} }
func (m *Mutation) String() string            { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()               {}
func (*Mutation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Mutation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Mutation) GetType() Mutation_Type {
	if m != nil {
		return m.Type
	}
	return Mutation_UNSPECIFIED
}

func (m *Mutation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Mutation) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DescriptorProto struct {
	SstMeta []*SstMeta `protobuf:"bytes,1,rep,name=sst_meta,json=sstMeta" json:"sst_meta,omitempty"`
}

func (m *DescriptorProto) Reset()                    { *m = DescriptorProto{} }
func (m *DescriptorProto) String() string            { return proto.CompactTextString(m) }
func (*DescriptorProto) ProtoMessage()               {}
func (*DescriptorProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DescriptorProto) GetSstMeta() []*SstMeta {
	if m != nil {
		return m.SstMeta
	}
	return nil
}

type SstMeta struct {
	// Filename is the name of the SST file, relative to the configured SST directory.
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	// The sequence number (inclusive) of mutations that have been applied.
	AppliedUntil int64 `protobuf:"varint,2,opt,name=applied_until,json=appliedUntil" json:"applied_until,omitempty"`
}

func (m *SstMeta) Reset()                    { *m = SstMeta{} }
func (m *SstMeta) String() string            { return proto.CompactTextString(m) }
func (*SstMeta) ProtoMessage()               {}
func (*SstMeta) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SstMeta) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *SstMeta) GetAppliedUntil() int64 {
	if m != nil {
		return m.AppliedUntil
	}
	return 0
}

func init() {
	proto.RegisterType((*LogRecord)(nil), "ddb.internal.LogRecord")
	proto.RegisterType((*Mutation)(nil), "ddb.internal.Mutation")
	proto.RegisterType((*DescriptorProto)(nil), "ddb.internal.DescriptorProto")
	proto.RegisterType((*SstMeta)(nil), "ddb.internal.SstMeta")
	proto.RegisterEnum("ddb.internal.Mutation_Type", Mutation_Type_name, Mutation_Type_value)
}

func init() { proto.RegisterFile("proto/internal.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x2d, 0x45, 0x28, 0x03, 0x4a, 0xb3, 0x41, 0xd3, 0xa8, 0x87, 0xa6, 0x5e, 0x7a, 0x30,
	0xc5, 0xd4, 0x47, 0x80, 0x9a, 0x60, 0xc0, 0x90, 0x05, 0x4e, 0x1e, 0xc8, 0x42, 0x47, 0xb3, 0xb1,
	0x7f, 0xd6, 0xee, 0xd6, 0x84, 0xa7, 0xf2, 0x15, 0x4d, 0x97, 0x82, 0x9a, 0x78, 0x9b, 0xef, 0xd7,
	0xc9, 0x2f, 0xd3, 0x6f, 0x61, 0x20, 0x8a, 0x5c, 0xe5, 0x43, 0x9e, 0x29, 0x2c, 0x32, 0x96, 0x04,
	0x3a, 0x92, 0x5e, 0x1c, 0x6f, 0x82, 0x03, 0xf3, 0x5e, 0xa0, 0x33, 0xcd, 0xdf, 0x28, 0x6e, 0xf3,
	0x22, 0x26, 0x57, 0x60, 0x49, 0xfc, 0x28, 0x31, 0xdb, 0xa2, 0x63, 0xb8, 0x86, 0x6f, 0xd2, 0x63,
	0x26, 0x21, 0x58, 0x69, 0xa9, 0x98, 0xe2, 0x79, 0xe6, 0x34, 0x5c, 0xc3, 0xef, 0x86, 0x97, 0xc1,
	0x6f, 0x53, 0x30, 0xab, 0xbf, 0xd2, 0xe3, 0x9e, 0xf7, 0x65, 0x80, 0x75, 0xc0, 0xc4, 0x06, 0xf3,
	0x1d, 0x77, 0xda, 0xdb, 0xa1, 0xd5, 0x48, 0x86, 0xd0, 0x54, 0x3b, 0x81, 0x5a, 0x77, 0x1e, 0x5e,
	0xff, 0xaf, 0x0b, 0x96, 0x3b, 0x81, 0x54, 0x2f, 0x92, 0x1b, 0xe8, 0x28, 0x9e, 0xa2, 0x54, 0x2c,
	0x15, 0x8e, 0xa9, 0x0f, 0xfc, 0x01, 0x64, 0x00, 0xa7, 0x9f, 0x2c, 0x29, 0xd1, 0x69, 0xba, 0x86,
	0xdf, 0xa3, 0xfb, 0xe0, 0xdd, 0x41, 0xb3, 0x32, 0x90, 0x3e, 0x74, 0x57, 0xcf, 0x8b, 0x79, 0x34,
	0x9a, 0x3c, 0x4e, 0xa2, 0xb1, 0x7d, 0x42, 0xda, 0x60, 0xce, 0x57, 0x4b, 0xdb, 0x20, 0x00, 0xad,
	0x71, 0x34, 0x8d, 0x96, 0x91, 0xdd, 0xf0, 0x46, 0xd0, 0x1f, 0xa3, 0xdc, 0x16, 0x5c, 0xa8, 0xbc,
	0x98, 0xeb, 0xbe, 0xee, 0xc1, 0x92, 0x52, 0xad, 0x53, 0x54, 0xcc, 0x31, 0x5c, 0xd3, 0xef, 0x86,
	0x17, 0x7f, 0x2f, 0x5d, 0x48, 0x35, 0x43, 0xc5, 0x68, 0x5b, 0xee, 0x07, 0xef, 0x09, 0xda, 0x35,
	0xab, 0x1a, 0x7d, 0xe5, 0x09, 0x66, 0x2c, 0xc5, 0xfa, 0xcf, 0x8f, 0x99, 0xdc, 0xc2, 0x19, 0x13,
	0x22, 0xe1, 0x18, 0xaf, 0xcb, 0x4c, 0xf1, 0x44, 0xf7, 0x60, 0xd2, 0x5e, 0x0d, 0x57, 0x15, 0xdb,
	0xb4, 0xf4, 0xa3, 0x3d, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x56, 0x1b, 0x5a, 0xcc, 0x01,
	0x00, 0x00,
}
